#!/bin/bash
#
#  fold The FOL Core server.
#
#
# chkconfig: 345 80 20
# description: fold
# processname: fold
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/fold, see below
if [ -f /etc/sysconfig/fold ]; then
        . /etc/sysconfig/fold
fi

RETVAL=0

prog=fold
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/fold
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/fold}

# fold defaults to /usr/bin/fold, override with BITCOIND_BIN
fold=${BITCOIND_BIN-/usr/bin/fold}

# fold opts default to -disablewallet, override with BITCOIND_OPTS
fold_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $fold $fold_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
